const SCOPES = [
  "creddits",
  "modcontributors",
  "identity",
  "modmail",
  "wikiread",
  "modconfig",
  "modlog",
  "modposts",
  "modothers",
  "modflair",
  "subscribe",
  "structuredstyles",
  "vote",
  "wikiedit",
  "mysubreddits",
  "submit",
  "save",
  "adsconversions",
  "read",
  "privatemessages",
  "report",
  "identity",
  "livemanage",
  "account",
  "modtraffic",
  "edit",
  "modwiki",
  "modself",
  "history",
  "flair",
];

module.exports = SCOPES;
